### ISSUE TITLE
Diff broken in v1.4.0

### ISSUE THREAD

**Issue by SRombauts** [SRombauts/UE4PlasticPlugin#56]
The diff feature is broken in v1.4.0 I recently released.
This affect Blueprint Visual Diff, as well as all other text base diff.

The issue appeared when I reworked the way the RepSpec of a file is retrieved, to support xlinks (see #55)
A relative filename is used to access the cached state of the file, but the cache requires absolute filenames.

**Comment by SRombauts** [comment]
Fix released in the version https://github.com/PlasticSCM/UE4PlasticPlugin/releases/tag/1.4.1

**Comment by ftrx** [comment]
Hi SRombauts,
thanks for your effort, unfortunately I still get the same error:
```
LogSourceControl: RunDumpToFile: 'cm cat revid:28984@ --raw --file="C:/Path/To/Unreal/Project/Saved/Diff/temp-28984-BP_MyBlueprintTest.uasset"'
LogSourceControl: RunDumpToFile: ExecProcess ReturnCode=1 Results=''
LogSourceControl: Error: RunDumpToFile: ExecProcess ReturnCode=1 Errors='Incorrect object specification revid:28984@
'
LogLinker: Warning: Can't find file 'C:/Path/To/Unreal/Project/Saved/Diff/temp-28984-BP_MyBlueprintTest.uasset'
```

here the complete log:  [output.log](https://github.com/SRombauts/UE4PlasticPlugin/files/2778145/output.log)

**Comment by SRombauts** [comment]
Sorry to hear that, any other info you can provide to help me find the issue?
Are you sure you properly updated to the latest release? Because this really looks like the same exact issue I have just fixed. And it seems to be working just fine on my end.

Anything special thing I should now about your setup?

**Comment by ftrx** [comment]
Hi Sebastien,
awesome! thank you a lot for your effort!

I've tested your last commit and the diff seems to work again, also for xlinks!

I'll test it in the next few days and keep you updated if I find anything.

cheers

**Comment by SRombauts** [comment]
Hey, great to hear, thanks for letting me know so fast!
